services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=codecake
      - POSTGRES_USER=codecake
      - POSTGRES_DB=airbnb_db
    ports:
      - 127.0.0.1:5432:5432
