logging:
  level:
    ROOT: INFO
    '[org.hibernate.SQL]': DEBUG
    '[fr.codecake.airbnbcloneback]': DEBUG

spring:
  profiles:
    active: dev
  application:
    name: airbnb-clone-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_db
    username: codecake
    password: codecake
    
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        '[default_schema]': public
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: public
    enabled: true
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-1m8rc8rkauzkk7c6.us.auth0.com/
    client-id: WNUDfBrJg6C46KxbhEmd8nK70y8eBZEg
    client-secret: Cgi8WarbeegjZfKDVpBPHbUZQnJAgXg8GAqSp0GG8Bhw-7a1a5EAQue15XqBxVDw
application:
  auth0:
    role-landlord-id: "rol_rSyLRkZ1gsnawxY4"