logging:
  level:
    ROOT: info
    '[org.hibernate.SQL]': INFO
    '[fr.codecake.airbnbcloneback]': INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airbnb_db
    username: codecake
    password: codecake
  jpa:
    properties:
      hibernate:
        '[default_schema]': public
  liquibase:
    contexts: prod
    default-schema: public